ocs:
  namespace: openshift-storage
  mon:
    requests:
       cpu: 1
       memory: 2Gi
  mds:
    requests:
      cpu: 3
      memory: 8Gi
  mgr:
    requests:
      cpu: 1
      memory: 3Gi
  noobaacore:
    requests:
      cpu: 1
      memory: 4Gi
  noobaadb:
    requests:
      cpu: 1
      memory: 4Gi
  osd:
    requests:
      cpu: 2
      memory: 5Gi
    pvc:
      storage: 2Ti
  storageClass:
    name: ocs-storagecluster-ceph-rgw
    region: us-west-1  #overwritten
    objectStoreName: ocs-storagecluster-cephobjectstore

toolbox:
  name: ocsinit
  enableCephTools: true

global:
  hub:
    region: us-west-1

clusterGroup:
  storageClass: gp2

#Define the odf storageSystem parameters
storageSystem:
  deploy: false
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
  spec:
    kind: storagecluster.ocs.openshift.io/v1
    name: ocs-storagecluster
    namespace: ""