global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: production
  isHubCluster: false
  storageClass: gp2

  namespaces:
    - rhacs-operator
    - stackrox
    - policies
    - devsecops-ci

  subscriptions:
    rhacs-operator:
      name: rhacs-operator  #packageName
      namespace: openshift-operators # operator namespace
      channel: rhacs-3.71

    quay-bridge-operator:
      name: quay-bridge-operator
      namespace: openshift-operators
      channel: stable-3.7

  projects:
    - app
    - secured

  applications:
    acs-secured:
      name: acs-secured
      namespace: stackrox
      project: secured
      path: charts/hub/acs/secured

    quay-integration:
      name: quay-integration
      namespace: openshift-operators
      project: secured
      path: charts/region/quay
