site:
  name: example

global:
  pattern: multicluster-devsecops
  repoURL: "https://github.com/<git-fork>/multicluster-devsecops"
  targetRevision: main

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main
    taskImage: image-registry.openshift-image-registry.svc:5000/openshift/tools

  app:
    gatling:
      image: quay.io/hybridcloudpatterns/gatling:latest
      repo: https://github.com/hybrid-cloud-patterns/spring-petclinic-gatling
    zapImage: quay.io/hybridcloudpatterns/zap2docker-stable
    crdaImage: quay.io/jchraibi/crda-image:0.1
    petclinic:
      repo: https://github.com/hybrid-cloud-demos/spring-petclinic
      configRepo: https://github.com/hybrid-cloud-demos/spring-petclinic-config
      image: quay.io/hybridcloudpatterns/spring-petclinic:latest

  # Should be set consistently with quay enterprise setup
  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  quay:
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: devel
      email: devel@myorg.com
    repo: example

devel:
  image: AUTOMATED
  namespace: AUTOMATED
  roxCTLImage: AUTOMATED

clusterGroup:
  name: testgroup
