{{- if $.Values.acs.integrations }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-acs-integrations-token
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipPrune
    argocd.argoproj.io/sync-wave: "7"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-api-token-configpolicy
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: acs-api-token
                  namespace: stackrox
                apiVersion: v1
                data:
                  token: '{{ `{{hub fromSecret "stackrox" "acs-api-token" "token" hub}}` }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: acs-integrations-token-placement-binding
placementRef:
  name: acs-integrations-token-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-acs-integrations-token
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acs-integrations-token-placement
spec:
  # This will go to all devel clusters
  clusterSelector:
    # Using matchLabels because I need it in only one clusterGroup
    matchLabels:
      clusterGroup: devel
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
{{- end }}
