apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
 name: quay
 annotations:
   argocd.argoproj.io/sync-wave: "8"
spec:
 clusterID: openshift
 credentialsSecret:
   name: quay-integration
   namespace: openshift-operators
# insecureRegistry: false
 insecureRegistry: true
 quayHostname: https://quay-registry-quay-quay-enterprise.{{ .Values.global.hubClusterDomain }}