apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: secured-cluster-secret-placement
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # This will go to all managed clusters
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable