apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: secured-cluster-secret-placement-binding
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "2"
placementRef:
  name: secured-cluster-secret-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: secured-cluster-secret-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io