apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
  # quaye is abbrev. for Quay Enterprise - diff from quayio
  name: create-quaye-pull-secret
  namespace: {{ .Values.quay.namespace }}
spec:
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        env:
        - name: QUAY_REPO
          value: "{{ .Values.global.quay.repo }}"
        command:
        - /bin/bash
        - -c
        - |
          oc wait QuayRegistry quay-registry --for=condition=Available=true
          '/tmp/create-quaye-pull-secret.sh'
        name: create-quaye-pull-secret
        volumeMounts:
          - mountPath: /tmp/create-quaye-pull-secret.sh
            name: create-quaye-pull-secret
            subPath: create-quaye-pull-secret.sh
      volumes:
        - name: create-quaye-pull-secret
          configMap:
            name: create-quaye-pull-secret
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: quay-admin-sa
      serviceAccountName: quay-admin-sa
      terminationGracePeriodSeconds: 400