---
apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "sonarqube.selectorLabels" . | nindent 4 }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.cicd.namespace }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
{{- include "sonarqube.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
