---
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: git-secret
  namespace: devsecops-ci
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: git-secret
    template:
      metadata:
        annotations:
          # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
          tekton.dev/git-0: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: {{ .Values.gitsecret.key }}