# The policy needs to be added to the ACM HUB and then it will be pushed on all clusters
# except the HUB (see placementrule on the bottom)
{{ if .Values.clusterGroup.isHubCluster }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-reports-nginx-secret
  namespace: {{ .Values.global.cicd.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipPrune
    argocd.argoproj.io/sync-wave: "15"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: reports-nginx-secret-policy
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
              - devsecops-ci
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: reports-nginx-htpasswd
                  namespace: {{ .Values.global.cicd.namespace }}
                apiVersion: v1
                data: 
                  htpasswd: '{{ `{{hub fromSecret "devsecops-ci" "reports-nginx-htpasswd" "htpasswd" hub}}` }}'
                
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: reports-nginx-secret-placement-binding
  namespace: devsecops-ci
placementRef:
  name: reports-nginx-secret-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-reports-nginx-secret
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: reports-nginx-secret-placement
  namespace: devsecops-ci
spec:
  # This will go to both devel and secured clusters
  clusterSelector:
    # Using matchExpression because I need it in more than one clusterGroup/cluster-group
    matchExpressions:
      - key: clusterGroup
        operator: In
        values:
          - devel
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
{{ end }}
