apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-storage-nodes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: label-storage-nodes
subjects:
  - kind: ServiceAccount
    name: label-storage-nodes
    namespace: {{ .Values.ocs.namespace }}

