apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: image-registry-credentials
metadata:
  name: pipeline-svc
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
secrets:
  - name: quay-api-token
  - name: acs-api-token
{{- if eq .Values.global.imageregistry.type "quay" }}
  - name: quay-pull-secret
{{- end }}