apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: build-tool
  name: syft-sbom
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to generate a SBOM file with Syft.
  params:
    - default: $(workspaces.source.path)
      description: Application folder to scan
      name: APP_PATH
      type: string
  steps:
    - image: 'registry.access.redhat.com/ubi8/ubi:latest'
      name: syft-scan
      resources: {}
      script: >
        #!/usr/bin/env bash

        echo '## Getting Syft ##' 

        pwd

        curl -sSfL
        https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s
        -- -b . 

        chmod +x ./syft

        echo '## Scanning folder and generating SBOM ##' 

        ./syft $(params.APP_PATH) -o spdx-json=sbom.json

        echo '## SBOM content ##' 

        cat ./sbom.json
  workspaces:
    - description: The workspace consisting of maven project.
      name: source
